### ISSUE TITLE
logo换一个绿色的是否更好看一些？

### ISSUE THREAD

**Issue by sunlianlong** [salamander-mh/SalamanderWnmp#10]
界面看起来是淡绿色，看起来还算挺好，但是右下角和状态栏里面灰色的狗头感觉有些不搭，另外灰色我个人感觉应该是服务离线的意思

另外咨询一下重启nginx是否是只能点击操作，而不能命令行操作，如果是的话建议能否在界面上命令行操作一些简单命令，比如说 nginx -t 等基本的测试功能
![image](https://user-images.githubusercontent.com/22101668/30802411-0d4a3236-a219-11e7-985a-bb00c4da0b1c.png)

**Comment by salamander-mh** [comment]
1. logo的话，因为自己没什么设计能力，所以找了个二哈的图片，哈哈（主题色是可以调的）
![image](https://user-images.githubusercontent.com/16663435/30804745-2312f870-a221-11e7-8687-6c17a4fa7ab1.png)

2.  命令行的问题的话，为了维持界面的简洁性，我尽量不加多余的按钮（或者有别的什么好的设计方案），我想到的是可以在点击Nginx的图片的时候，打开Windows命令行（路径定位到nginx的目录下），其实点击MySQL的图片是可以打开MySQL Client的（不知道你发现没^—^）
