### ISSUE TITLE
php.ini问题

### ISSUE THREAD

**Issue by yyblove** [salamander-mh/SalamanderWnmp#13]
默认配置， php.ini 被指向了 C:\Windows 了， 请问这个要怎么修改？

**Comment by yyblove** [comment]
呃， 是  Loaded Configuration File 没有指向到我配置的目录，显示为空
windows10.  
存放目录: D:\Program Files\SalamanderWnmp
php的配置没有使用 D:\Program Files\SalamanderWnmp\php\php.ini

**Comment by salamander-mh** [comment]
你的wnmp目录可能被移动过了，重新装一个即可

**Comment by yyblove** [comment]
目录是没有被移动的。 我 把程序放到D盘下面， 就可以了。 应该是我的目录有空格引起的， 之前的版本也没有这个问题啊
