### ISSUE TITLE
是否可以集成最新版本

### ISSUE THREAD

**Issue by adgad2** [salamander-mh/SalamanderWnmp#14]
能否集成一份最新php+mysql+nginx的版本？  

或者大概说说如何更新

**Comment by yyblove** [comment]
README 有说明如何更新了。 我想问下， 你的 php.ini 的配置文件的地址有生效吗？

**Comment by salamander-mh** [comment]
README 有说如何更新PHP了

**Comment by adgad2** [comment]
@yyblove   这个没有修改过，得回家测试一下

@salamander-mh 其实我想升级的mysql的版本，想使用5.7的版本，是不是和php类似的安装然后改目录就好了？

**Comment by salamander-mh** [comment]
更新MySQL，你需要把原来的_MySQL服务_删除，名为mysql-salamander
请以管理员运行：
```
sc delete mysql-salamander
```
然后配置文件中修改：
```
; First run
firstRun=False

 Mysql directory name
mysqlDirName=mysql
```
**firstRun**改为true，**mysqlDirName**改为php5.7（就是你新的MySQL目录名）
