### ISSUE TITLE
关于redis集成连接问题

### ISSUE THREAD

**Issue by adgad2** [salamander-mh/SalamanderWnmp#16]
首先，php好像是没有集成redis扩展的吧？我尝试手动安装
在redis中执行info命令，显示
```
# Server
redis_version:3.2.100
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:dd26f1f93c5130ee
redis_mode:standalone
os:Windows
......
```
得知redis版本为3.2.100，然而我去 https://windows.php.net/downloads/pecl/releases/redis/ 下载扩展的时候，发现没有这个版本对应的扩展
http://windows.php.net/downloads/pecl/releases/igbinary  这里是可以找到对应版本的

那么我是重新自己安装redis吗？   有注意的地方吗？

**Comment by adgad2** [comment]
使用3.1.6的版本成功了，好像是我没重启的问题

话说手动退出软件不会杀死进程吗？  我是关闭软件后手动杀进程才重启成功的，还是说我电脑的问题

**Comment by salamander-mh** [comment]
推出软件不会退出进程，其他进程也都不会
