### ISSUE TITLE
Windows 10 下设置菜单内的MySQL命令行密码更改无效问题

### ISSUE THREAD

**Issue by snakeysky** [salamander-mh/SalamanderWnmp#18]
经过测试，命令行密码修改后点保存设置，默认root密码仍旧为空。

**Comment by salamander-mh** [comment]
@snakeysky  我这里没问题
![image](https://user-images.githubusercontent.com/16663435/39803226-fb24b81a-53a2-11e8-9793-4807940ce409.png)

![image](https://user-images.githubusercontent.com/16663435/39803238-061bd97e-53a3-11e8-9ea9-0cb83935e420.png)

**Comment by salamander-mh** [comment]
@snakeysky  这个应该没有关系

**Comment by snakeysky** [comment]
@salamander-mh 
我又试了下，还是不行，修改时需要启动着mysql服务还是不启动状态？

**Comment by salamander-mh** [comment]
忘记说了，用新版的MySQL，你需要把原来的MySQL服务删除掉，把设置中mysql目录修改下，然后退出wnmp，
![image](https://user-images.githubusercontent.com/16663435/39848717-2328efb4-543b-11e8-8064-eccdd722028a.png)

![image](https://user-images.githubusercontent.com/16663435/39848671-dc2da5dc-543a-11e8-8518-cbedce2c1272.png)
使用命令：
```
sc delete mysql-salamander
```
因为wnmp程序是通过windows服务控制mysql进程的

**Comment by snakeysky** [comment]
Soga,另希望可以加上开机启动，这样就可以无人值守了。虽然现在也可以用计划任务来解决。。。

**Comment by snakeysky** [comment]
Soga,另希望可以加上开机启动，这样就可以无人值守了。虽然现在也可以用计划任务来解决。。。

**Comment by snakeysky** [comment]
可以删服务但还是用原来的目录么？

**Comment by salamander-mh** [comment]
你要换新的版本的MySQL，就要把`mysql-salamander`这个服务删掉，wnmp重启会添加一个新的

**Comment by snakeysky** [comment]
Soga~了解了，多谢。
