### ISSUE TITLE
Windows 10 下设置菜单假死导致程序无响应关闭的问题

### ISSUE THREAD

**Issue by snakeysky** [salamander-mh/SalamanderWnmp#19]
经多次测试，在自行添加php5.4或5.6，并在设置中修改目录名后，若未在php.ini内指定扩展dll的目录，此时点击右上角“箭头”--“设置”时会立刻引起程序假死。再次开启程序重复上述操作后仍会假死，需要先关闭在运行状态的php与nginx服务后，才能正常进入设置菜单。也出现过即使关闭服务也继续无响应假死的情况，删除程序根目录Wnmp.ini后可以恢复。

**Comment by snakeysky** [comment]
原来如此，了解了。

**Comment by snakeysky** [comment]
原来如此，了解了。

**Comment by salamander-mh** [comment]
点击之前，我加判断好了
