### ISSUE TITLE
建议修改下nginx.conf里面POST最大数据

### ISSUE THREAD

**Issue by yuewolf** [salamander-mh/SalamanderWnmp#5]
client_max_body_size

如果再增一下常见CMS的CONF就更好了。

LNMP.ORG自带的就很贴心。

我觉得如果更傻瓜一点，一定更多人喜爱。

**Comment by salamander-mh** [comment]
收到建议了，client_max_body_size会添加进去的。
其他常见CMS的CONF我也会添加的
