### ISSUE TITLE
mysql 无法启动计算机“DESKTOP-G6SN9SC”上的服务 mysql-salamander。

### ISSUE THREAD

**Issue by vin1992** [salamander-mh/SalamanderWnmp#6]
mysql 无法启动计算机“DESKTOP-G6SN9SC”上的服务 mysql-salamander。  具体是什么原因呢?

**Comment by salamander-mh** [comment]
查看windows服务中有没有mysql-salamander这个服务

**Comment by salamander-mh** [comment]
这个问题的原因是，首次运行了之后，把wnmp文件夹的路径移动了

**Comment by Macsgl** [comment]
@salamander-mh 请问需要怎么解决呢

**Comment by salamander-mh** [comment]
可以重新下载wnmp包,首次运行会自动配置的
